AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'db/*'
    - Gemfile

Layout/LineLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: true
  Max: 20

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/RedundantFreeze:
  Enabled: true
