images:
  default_user_avatar_url: https://amshan-storage-development.ams3.digitaloceanspaces.com/default_avatar.png
  default_entity_logo_url: https://amshan-storage-development.ams3.digitaloceanspaces.com/default_company.png
